### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by ujaved** [yongliang-wu/MM-VID#1]
Hi. Thanks for the code.
I don't think the dependencies listed in `requirements.txt` are set up properly. After adding the missing `opencv-python` I get the error:

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/ujaved/MM-VID/main.py", line 2, in <module>
    from moviepy.editor import VideoFileClip
  File "/Users/ujaved/MM-VID/lib/python3.12/site-packages/moviepy/editor.py", line 48, in <module>
    import moviepy.video.fx.all as vfx
  File "/Users/ujaved/MM-VID/lib/python3.12/site-packages/moviepy/video/fx/all/__init__.py", line 17, in <module>
    exec("from ..%s import %s" % (name, name))
  File "<string>", line 1, in <module>
  File "/Users/ujaved/MM-VID/lib/python3.12/site-packages/moviepy/video/fx/headblur.py", line 5, in <module>
    import cv2
  File "/Users/ujaved/MM-VID/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Users/ujaved/MM-VID/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
AttributeError: _ARRAY_API not found
```

**Comment by yongliang-wu** [comment]
Please try the following command
```shell
pip uninstall numpy

pip install numpy<2
```
